### ISSUE TITLE
Can't remove blobs from custom model

### ISSUE THREAD

**Issue by oovm** [podgorskiy/StyleGAN_Blobless#1]
### Steps to Reproduce

download model from:

https://mega.nz/#!0JVxHQCD!C7ijBpRWNpcL_gubWFR-GTBDJTW1jXI6ThzSxwaw2aE

set resolution=512 here:

https://github.com/podgorskiy/StyleGAN_Blobless/blob/3bf6f225a493df42d262743e5d41cb91f1c5c33c/convertor.py#L57

use config following:

```yaml
MODEL:
  LATENT_SPACE_SIZE: 512
  LAYER_COUNT: 8
  MAX_CHANNEL_COUNT: 512
  START_CHANNEL_COUNT: 32
  DLATENT_AVG_BETA: 0.995
  MAPPING_LAYERS: 8
OUTPUT_DIR: .
```

---

The final result doesn't seem to make any difference, (at least I can't see), blobs still there.

![](https://user-images.githubusercontent.com/17541209/71543782-29c64a80-29b2-11ea-8ad2-beae5b019342.png)

Can you help me fix this model? Thanks!
